### ISSUE TITLE
🖼️ Stations photo status

### ISSUE THREAD

**Issue by GuyNoimark** [guytepper/better-rail#100]
All the train stations from [Israel Railways website](https://www.rail.co.il/stationnlines) are listed here.
Stations that have images in the app are marked with a checkmark - hopefully it will be much easier to add the missing ones :)

- [x] אופקים
- [x] אחיהוד
- [x] אשדוד - עד הלום
- [ ] אשקלון
- [x] באר יעקב
- [x] באר שבע - מרכז
- [x] באר שבע - צפון / אוניברסיטה
- [x] בית יהושע
- [ ] בית שאן
- [x] בית שמש
- [x] בני ברק
- [ ] בנימינה
- [x] בת ים - יוספטל
- [x] בת ים - קוממיות
- [ ] דימונה
- [x] הוד השרון - סוקולוב
- [x] הרצלייה
- [ ] חדרה - מערב
- [x] חולון - וולפסון
- [x] חוצות המפרץ
- [x] חיפה - בת גלים
- [x] חיפה - חוף הכרמל (ש' רזיאל)
- [ ] חיפה מרכז - השמונה
- [ ] יבנה - מזרח
- [x] יבנה - מערב
- [ ] יקנעם - כפר יהושע

**Comment by guytepper** [comment]
Hey! Big thanks for taking the time creating this list, but we already have an [active list](https://github.com/guytepper/better-rail/issues/81) with the missing station images :) I'll pin that issue so hopefully it will attract more attention
