### ISSUE TITLE
iOS app white out

### ISSUE THREAD

**Issue by knqyf263** [guytepper/better-rail#102]
I installed and opened Better Rail, but it just shows only a white screen as below.

![IMG_AB95CF3F03F8-1](https://user-images.githubusercontent.com/2253692/219273636-9415e0d0-7e18-4222-a641-e21eb6a2671b.jpeg)

I tried to uninstall and install it again, but it showed the same.

iOS: 16.1.1
iPhone: 12

Please let me know if you need other information.

**Comment by guytepper** [comment]
were you using the app before, or is it a fresh install? is that a beta version by any chance? are you using a VPN?

**Comment by knqyf263** [comment]
Thanks for the quick response.
- fresh install
- version: 1.9.3
- no VPN

**Comment by guytepper** [comment]
first time I'm seeing this report, very strange! it's not crashing, right? just stuck on the white screen? maybe restarting the device would help? 
mind if I'll send you a link to the beta (via email), see if it changes anything?
