### ISSUE TITLE
On initial launch restart, the app quits instead of reloading

### ISSUE THREAD

**Issue by guytepper** [guytepper/better-rail#32]
On initial launch we need to reload the app in order to get the RTL layout working (see https://github.com/guytepper/better-rail/blob/main/app/app.tsx#L33-L42). 

However, on android release builds the app just quits - and it's not coming back unless we open the app again. From there everything works fine.

I've opened an issue about this over at https://github.com/avishayil/react-native-restart/issues/164, but it might be something on our side (?)

**Comment by guytepper** [comment]
Resolved via #33

**Comment by rodinhatokay** [comment]
@guytepper hey im having same issue with my app and its RTL too any idea can you explain how did you fix?

**Comment by guytepper** [comment]
Hey @rodinhatokay, I'm not sure if that's what fixed it, but [delaying the restart invocation](https://github.com/guytepper/better-rail/blob/main/app/i18n/i18n.ts#L66-L71) seemed to make it work
