### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by guytepper** [guytepper/better-rail#34]
The translation keys resides in [i18n/he.json](https://github.com/guytepper/better-rail/blob/main/app/i18n/he.json) (english also exists at [i18n/en.json](https://github.com/guytepper/better-rail/blob/main/app/i18n/en.json)).

To translate the app you need to create a `ru.json` file in the `i18n` folder, copy the keys from the other translation file and write the translation in Russian :)

**Note: No need to translate the `newFeature` strings**

If you have experience with React Native, the following tasks also needs to be done - but if you can only contribute the translation strings it's perfectly good! I can do the other parts by myself :)

- [ ] Verify the layout looks correctly
- [ ] Add support for station names
- [ ] Make sure the date & numbers displays correctly
- [ ] Test language switching
- [ ] Translate store's description & screenshots

**Comment by De1ain** [comment]
Hi @guytepper,
I'd like to work on this one, please assign to me.

**Comment by guytepper** [comment]
Hey @De1ain, thanks! Feel free to take it :-) 
Looking forward for your PR!

**Comment by guytepper** [comment]
Resolved via #87
