### ISSUE TITLE
Tomorrow should be written with a capital T

### ISSUE THREAD

**Issue by Aric5301** [guytepper/better-rail#46]
The app is great!
When scheduling a trip, "Tomorrow" should have a capital T.
![Screenshot_20210602-101848__01.jpg](https://user-images.githubusercontent.com/25414752/120440529-50996500-c38c-11eb-9607-20210dd119d1.jpg)

Thanks :)

**Comment by guytepper** [comment]
Thanks for the report :)
The `tomorrow` string comes from [date-fns `formatRelative` localization](https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/formatRelative/index.js#L5). If we want to fix the issue I guess we'll have to override it, as explained [here](https://stackoverflow.com/questions/47244216/how-to-customize-date-fnss-formatrelative).

**Comment by guytepper** [comment]
closing this - don't want us to handle this edge case (+ I actually love the lower case style!)
