### ISSUE TITLE
Can't change time of search to the past

### ISSUE THREAD

**Issue by LidorDublin** [guytepper/better-rail#54]
When I try to search for trains that departed earlier than `now`, it just scrolls back the clock to `now`.
e.g. When I'm on a train and I want to see the arrival time after the train already departed. 

Seems to be consistent And reproduceable.

App version 1.3.3, Android 11, OneUI version 3.1

**Comment by guytepper** [comment]
Hey :) That's intentional, because Israel Railways API ignores the requested hour - it always returns the remaining train times for the day, without the departed trains.
