### ISSUE TITLE
Add an option to delete a favorite route 

### ISSUE THREAD

**Issue by guytepper** [guytepper/better-rail#68]
<img src="https://user-images.githubusercontent.com/13344923/136766642-823bf3fb-f3d0-42f3-96be-8000cb355b5d.png" width="250" align="right">Similiar to iOS, the Android version should be an option to delete a favorite route right from the "select station" screen.

The `Delete` option be placed instead of the `Cancel` option (the sheet can be dismissed in other ways) and it should have red, destructive color.

## 🧐 How to approach:
1. The action sheet code resides in the [`favorite-route-box`](https://github.com/guytepper/better-rail/blob/082bc7b4999f6b440d4f6a149b6dc09e76829fe3/app/components/favorite-routes/favorite-route-box.tsx#L214-L227) file.
2. Check the [`react-native-action-sheet`](https://github.com/expo/react-native-action-sheet) docs to see how the action sheet component works.
3. Add the the `Delete` option to the action sheet. Don't forget to make sure it's styled as a `destructive` option.
4. A delete route method is [already implemented](https://github.com/guytepper/better-rail/blob/082bc7b4999f6b440d4f6a149b6dc09e76829fe3/app/components/favorite-routes/favorite-route-box.tsx#L127-L132), it's just need to be called when the option is pressed.

## 💡 Things to keep in mind:
1. The delete action string should be displayed in the current user locale.
The translated string is ready for use under `common.delete` with the `translate()` method

**Comment by De1ain** [comment]
@guytepper, I'd like to work on this issue, please assign to me.

**Comment by guytepper** [comment]
@De1ain awesome! It's yours :)

**Comment by guytepper** [comment]
Resolved via #90; thanks @De1ain!
