### ISSUE TITLE
Typo in one of the app marketing photos on the App Store

### ISSUE THREAD

**Issue by liorazi** [guytepper/better-rail#69]
Current: חשבו מסלולי נסיעה במהירת

Expected: חשבו מסלולי נסיעה במהירות
![Screen Shot 2021-10-12 at 16 02 24](https://user-images.githubusercontent.com/2930153/136961442-63e4b9b6-4262-4891-b5a1-72bec06cd162.png)

**Comment by guytepper** [comment]
Thank you! funny how it passed unnoticed by me. 
I've fixed the screenshots, it'll be updated in the next release :)
