### ISSUE TITLE
Add platform in search window 

### ISSUE THREAD

**Issue by joroMaser** [guytepper/better-rail#83]
Please add number of platform in the search window under "no exchange" line

There is no need to press on the line too see the platform

**Comment by guytepper** [comment]
Hey! Thanks for the suggestion. 
I wanted to keep the route list clean and not overload it with data. 
Also, when looking at the various train options, the average user won't care which platforms they depart from - they'd want to see the various train times available - then gather more information from the specific entry. So I believe it's better to leave it as it is.
