### ISSUE TITLE
Make station name clickable for new search

### ISSUE THREAD

**Issue by joroMaser** [guytepper/better-rail#85]
![4922 (2)](https://user-images.githubusercontent.com/14313895/154843979-948f5820-bd4f-41ba-8416-c48fc6e4a1ba.jpg)
I think it's good idea to makes the plaftom(marked) clickable to new search.

**Comment by guytepper** [comment]
Thanks for the suggestion! 
Putting it up for grabs since I won't have time to work on this in the upcoming weeks

**Comment by De1ain** [comment]
Hi @guytepper, I'd like to work on this issue, please assign it to me.

**Comment by De1ain** [comment]
Hi @guytepper, I'd lke to try implementing it.

**Comment by guytepper** [comment]
Hey @De1ain! That's awesome, it's all yours :)

Let me know if you need any guidance on implementing it

**Comment by guytepper** [comment]
Hey @De1ain, would you still like to work on it? 
I want to get this feature into the next release, so if you won't be able to work on it by the next weekend I'll take it :)

**Comment by De1ain** [comment]
@guytepper, I'm still trying to make it work.
Sorry I'm taking so long, never worked with React Native before.

**Comment by guytepper** [comment]
Feel free to open a pull request and mark it as work in progress. I can help guide you through the struggles :)

**Comment by frankykubo** [comment]
Hello, is this issue still relevant? I would like to contribute if its available as a part of my study examination. Thank you!

**Comment by guytepper** [comment]
Hey @frankykubo, I prefer to leave it as it is for now. If you'd like to contribute for another feature let me know and I'll come up with something :)

**Comment by frankykubo** [comment]
Thanks for your response @guytepper . I would like to. If you have any TODO list with possible implementations / refactoring, you can paste it below or on my email - frankykubo@gmail.com. Thank you! :)
