### ISSUE TITLE
Russian translation for iOS Widget & Apple Watch App

### ISSUE THREAD

**Issue by guytepper** [guytepper/better-rail#88]
Now that the app is translated to Russian (via #87), it'll be nice to support it in the iOS Widget & the Apple Watch app.

The strings to localize are located in the following files:
[`/ios/ru.lproj/Localizable.strings`](https://github.com/guytepper/better-rail/blob/844d68ac315d6a38c7c844239430ac639ff0ae05/ios/ru.lproj/Localizable.strings)
[`/ios/BetterRailWidget/ru.lproj/Route.strings`](https://github.com/guytepper/better-rail/blob/844d68ac315d6a38c7c844239430ac639ff0ae05/ios/BetterRailWidget/ru.lproj/Route.strings)

Then Russian needs to be added as a supported language in the code in the following files:
`Utilities.swift`
`StationModel.swift`

One thing be aware of is that long Russian strings could make some text elements to overflow, sinceapple watch apps & widgets doesn't have lots of screen space

**Comment by De1ain** [comment]
Hi @guytepper,
I can do that, but unfortunately I won't be able to test it.

**Comment by guytepper** [comment]
That'd be great @De1ain! 
No worries, I'll test your changes :)

**Comment by guytepper** [comment]
Resolved via #89
