### ISSUE TITLE
Application crashed each morning 

### ISSUE THREAD

**Issue by joroMaser** [guytepper/better-rail#95]
Version 1.9.0. . ANDROID 11
Each morning I enter to application it crash and when I reopen it , everything fine.
I don't have any more details.

**Comment by guytepper** [comment]
Has it happened before v1.9.0? 
What's the app language you're using?

**Comment by joroMaser** [comment]
I  don't sure what's happend before 1.9.0. I saw that 1.9.0 publish 4 days ago, I think it's happend during last week.

I use Hebrew language
