### ISSUE TITLE
Refresh train schedule list

### ISSUE THREAD

**Issue by guytepper** [guytepper/better-rail#97]
The schedule in the `RouteListScreen` needs to have a pull to refresh option. 

This could be achieved through adding an [`onRefresh`](https://reactnative.dev/docs/flatlist#onrefresh) callback to the `FlatList` component, which will invalidate the `react-query` cache for the specific route key.

**Comment by frankykubo** [comment]
@guytepper this looks good. I looked more deeply in the readme and I am not an iPhone user though. Do you think I can work on this just on an Android device?

**Comment by guytepper** [comment]
Yup! I'll test your changes on my iPhone :)

**Comment by guytepper** [comment]
hey @frankykubo, any updates about this one? :)

**Comment by frankykubo** [comment]
Hey @guytepper , since there was other appropriate issue for my study work in React+Typescript, which I prefer, I've started doing in that, so if anybody wants to work on this, its free. :) Thank you !!

**Comment by guytepper** [comment]
Added via 4f41bcb3b09f1ad9f2d0c0d7d8612bab7dfbc60e
