### ISSUE TITLE
Staion 0 in Be'er-Sheva

### ISSUE THREAD

**Issue by joroMaser** [guytepper/better-rail#98]
![Screenshot_20221102-171824_Better Rail](https://user-images.githubusercontent.com/14313895/199528971-e32a52d6-a709-44f3-b73d-bfa46762fcbf.jpg)

When I search rail from Be'er-Sheva Center I got that the source station is 0

Version :1.9.3

**Comment by guytepper** [comment]
Hey! Thanks for the report.

I see in the official website that it says the platform isn't decided yet (which probably symbolized by 0 in the API)
<img width="334" alt="Screen Shot 2022-11-03 at 12 55 35" src="https://user-images.githubusercontent.com/13344923/199703373-739938b7-9ff3-4325-a482-82ee5de20b82.png">
Is the schedule in the train station shows something different? How did you know on which platform to wait for the train?

**Comment by joroMaser** [comment]
> Hey! Thanks for the report.
> 
> I see in the official website that it says the platform isn't decided yet (which probably symbolized by 0 in the API) <img alt="Screen Shot 2022-11-03 at 12 55 35" width="334" src="https://user-images.githubusercontent.com/13344923/199703373-739938b7-9ff3-4325-a482-82ee5de20b82.png"> Is the schedule in the train station shows something different? How did you know on which platform to wait for the train?

I saw it on the electronic board. 
If the API don't give that information maybe it will be better to write "-" or something else instead of 0

**Comment by guytepper** [comment]
Okay, let's add `Uknown platfform` / `רציף לא ידוע` when the platform is `0`
